### ISSUE TITLE
Alltalos triggers one build per talos job

### ISSUE THREAD

**Issue by glandium** [armenzg/mozilla_ci_tools#120]
I ran this:
alltalos.py --repo-name try --times 2 --rev 921277f744d9

921277f744d9 had one Windows build and one Talos job prior to that.
That command line triggered the expected talos jobs for that windows build, but it also triggered 6 win64 *builds*, 3 android *builds* and 16 mac *builds*
Interestingly, it didn't trigger Linux builds.

**Comment by glandium** [comment]
> Interestingly, it didn't trigger Linux builds.

... despite saying it would, for example:
03/12/2015 10:51:50 INFO:	 We want to trigger 'Ubuntu HW 12.04 try talos g1' on revision '921277f744d9' a total of 2 time(s).
03/12/2015 10:51:54 INFO:	 We are going to trigger Linux try build instead of Ubuntu HW 12.04 try talos g1

**Comment by glandium** [comment]
Actually, while at the time I wrote the comment about Linux builds, neither buildapi nor treeherder were showing Linux builds, they did happen... all six of them for each of Linux/Linux x64.

**Comment by glandium** [comment]
and no talos job ran for those builds.

**Comment by jmaher** [comment]
talos (or any unittest) jobs don't magically happen after a build- we would need a server listening for the 'build finished' and then schedule the talos job.  For integration branches we default to scheduling a full set of unittest/talos jobs upon 'build finished', that is built into the scheduler.

what is concerning is that we triggered a bunch of builds- that is something we need to address somewhere.  I assume throughout all our scripts.

One thought I had here is we could build a list of all the jobs we need to run after inspecting them.  In this case it would translate to a list of builds.  If we didn't specifically ask for builds from the CLI, we could de-duplicate the list.

I see this being a list of:
{'jobname': {'revision': xyz, 'prerequisite_build': true}, 'jobname': {}}

in the de-duplication, we could find all prerequisite_build jobs and ensure we only schedule one.

**Comment by armenzg** [comment]
From the comments I believe your checkout is out of date as I fixed the issue of triggering multiple builds last week,
https://github.com/armenzg/mozilla_ci_tools/issues/90#issuecomment-77407428

**Comment by armenzg** [comment]
Does this happen if you're up-to-date?

**Comment by glandium** [comment]
I cloned yesterday, and the tip was:
https://github.com/armenzg/mozilla_ci_tools/commit/2a8289a156538a1ea18aa53971578ab9c99213f6

**Comment by armenzg** [comment]
Thanks for the information.
I will look into this tomorrow.

For my own reference:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=921277f744d9

**Comment by armenzg** [comment]
On another note, you're in a timezone where you could actually be hitting issue #46

**Comment by armenzg** [comment]
I actually realized that you might do me a huge favour if your run that script with --debug --dry-run.
You should push around 3:30pm Pacific time and run the script past 10pm Pacific time.

Even if we get the timing wrong, the output would be very beneficial for me!

**Comment by glandium** [comment]
I did a push around 3:30pm but ran the script slightly after 12pm. I hope the log will be useful anyways.
This is with 4337777bb8e9ede7d9e5b2f8e2e2a7e6bf4fb538 (unmodified)
https://gist.github.com/glandium/11b6ce53941f4fe70f21

**Comment by armenzg** [comment]
With the optimization mentioned on issue #122 I will partially be able to fix this.

**Comment by armenzg** [comment]
I will be working on this.

**Comment by armenzg** [comment]
I have fixed this issue with this:
https://github.com/armenzg/mozilla_ci_tools/commit/11a69008020c9fcb31b7bdd6248149569a3b2d5e

We now make sure that we don't trigger *build* jobs multiple times during the same run (a.k.a. session).

You will now have messages like this "We have already scheduled the build Android armv7 API 11+ ash build for revision bb1e5f9c6caf during this session. We don't allow multiple requests.".

armenzg@armenzg-thinkpad:~/repos/ci_tools$ python scripts/alltalos.py --repo-name ash --rev bb1e5f9c6caf --times 2 | tee output.txt
03/26/2015 12:23:56 INFO:	 We want to trigger 'Android 4.0 armv7 API 11+ ash talos remote-tp4m_nochrome' on revision 'bb1e5f9c6caf' a total of 2 time(s).
03/26/2015 12:23:57 INFO:	 We are going to trigger 'Android armv7 API 11+ ash build' instead of 'Android 4.0 armv7 API 11+ ash talos remote-tp4m_nochrome'
03/26/2015 12:23:57 INFO:	 We want to trigger 'Android 4.0 armv7 API 11+ ash talos remote-trobocheck2' on revision 'bb1e5f9c6caf' a total of 2 time(s).
03/26/2015 12:23:58 INFO:	 We are going to trigger 'Android armv7 API 11+ ash build' instead of 'Android 4.0 armv7 API 11+ ash talos remote-trobocheck2'
03/26/2015 12:23:58 INFO:	 We have already scheduled the build Android armv7 API 11+ ash build for revision bb1e5f9c6caf during this session. We don't allow multiple requests.
03/26/2015 12:23:58 INFO:	 We want to trigger 'Android 4.0 armv7 API 11+ ash talos remote-tsvgx' on revision 'bb1e5f9c6caf' a total of 2 time(s).
03/26/2015 12:23:59 INFO:	 We are going to trigger 'Android armv7 API 11+ ash build' instead of 'Android 4.0 armv7 API 11+ ash talos remote-tsvgx'
03/26/2015 12:23:59 INFO:	 We have already scheduled the build Android armv7 API 11+ ash build for revision bb1e5f9c6caf during this session. We don't allow multiple requests.
