### ISSUE TITLE
alltalos is very slow

### ISSUE THREAD

**Issue by glandium** [armenzg/mozilla_ci_tools#122]
Running:
alltalos.py --repo-name try --times 2 --rev 921277f744d9

took, overall, 7 minutes and a half.

**Comment by glandium** [comment]
- https://hg.mozilla.org/try/json-pushes?changeset=...&tipsonly=1&full=1?changeset=775753be3604&tipsonly=1&full=1 is fetched once per talos job type.
- https://secure.pub.build.mozilla.org/buildapi/self-serve/try/rev/...?format=json is fetched once per talos job type.
- http://builddata.pub.build.mozilla.org/builddata/buildjson/builds-4hr.js.gz looks like it's supposed to be fetched once a minute, but the file is still fetched once per talos job type because the file is always downloaded, whether or not the local copy exists.

**Comment by jmaher** [comment]
great find- we need to find ways to optimize this- likely the same solution will be needed for other scripts!

**Comment by armenzg** [comment]
If you pull the latest code, there are some optimizations.

I can help reduce these numbers with a bit of smarted code paths.

The remaining performance improvements can only come once we paralellize the handling of each revision instead of sequentially processing them. I was to add this to the roadmap as part of issue #86 .

**Comment by glandium** [comment]
Still took five minutes for https://github.com/armenzg/mozilla_ci_tools/issues/120#issuecomment-78842896

**Comment by armenzg** [comment]
Thank you. I will be away next week but I hope to improve this before the end of the month.

**Comment by armenzg** [comment]
I have found a way to optimize this many many times.

We currently iterate one builder at a time.
This means that we have to discover its associated build for each builder of that platform.
It might take me a couple of days but the performance improvement will be big.

**Comment by armenzg** [comment]
FYI I will be away next week.

**Comment by armenzg** [comment]
If anyone wants to pick this up while am gone:

Call trigger_range() with a list of builders instead of just one builder.
Create a function that will allow you to create lists of builders depending on which build job triggers them.
Now, given that you have a list of builders and the build job that would trigger them, calculate if the build exists. If the build exists, you willd grab the associated files to trigger each of those builders (since they are all triggered by the same build).

This is a bit of a refactor but it will make things much nicer,

**Comment by armenzg** [comment]
This change significantly improves the execution time of alltalos the more jobs there are on a push (pushes older than today):
https://github.com/armenzg/mozilla_ci_tools/commit/468a5f75c3483273e84e50edbab780818769d38b

We might have some more performance gains this week.

**Comment by armenzg** [comment]
After further thinking, the highest gain has been obtained.
For further optimizations I have filed issue 143.
