### ISSUE TITLE
Add support for Pulse

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#126]
This would be needed to monitor jobs:
https://pulse.mozilla.org

**Comment by adusca** [comment]
Test informant does it like this: https://github.com/mozilla/test-informant/blob/master/informant/pulse_listener.py

**Comment by adusca** [comment]
I wrote a simple proof of concept for pulse support: https://github.com/armenzg/mozilla_ci_tools/compare/armenzg:master...adusca:pulse?expand=1

**Comment by armenzg** [comment]
Hi Alice, thanks for your Pulse POC. It helps me understand this a bit better.
For now, let's not add it to this script.
Let's separate the requesting of credentials into its own function.

Let's create a misc script which will use pulse.
We should use it to trigger a builder on Cedar and monitor it and log every time it changes states: requested, pending, running, completed. The script would stop once we get to the completed state.

Also have you seen this? We should use the NormalizedBuildConsumer consumer instead of the Generic one.
https://wiki.mozilla.org/Auto-tools/Projects/Pulse#Consuming_Buildbot_messages
https://github.com/mozilla/pulsetranslator

It seems to have 3 routing keys:
unittest.%tree%.%platform%.%os%.%buildtype%.%testname%.%product%.%builder%
talos.%tree%.%platform%.%os%.%buildtype%.%testname%.%product%.%builder%
build.%tree%.%platform%.%buildtype%.%builder%

I don't know if only 3 routing keys would be limiting or not. The day we have users using the pulse support we can determine if there's anything lacking.

**Comment by adusca** [comment]
I made a few changes and created the script listen_and_trigger. I'm testing with try (I believe I'm not allowed to retrigger jobs anywhere else). I was only able to show a completed job message, because that is what shows up in the exchange.

This is the output I get:
alice@alice-UX303LN:~/mozilla_ci_tools$ python scripts/list_and_trigger.py -b "Ubuntu VM 12.04 try opt test marionette" -r 2d3659c2b21c
Please type your pulse username: adusca
Pulse password: 
03/24/2015 05:40:45 INFO:	 We want to have 2 job(s) of Ubuntu VM 12.04 try opt test marionette on revisions ['2d3659c2b21c']
03/24/2015 05:40:45 INFO:	 
03/24/2015 05:40:45 INFO:	 === 2d3659c2b21c ===
03/24/2015 05:40:45 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/24/2015 05:40:47 INFO:	 We want to have 2 job(s) of Ubuntu VM 12.04 try opt test marionette on revision 2d3659c2b21c
03/24/2015 05:40:47 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/24/2015 05:40:48 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/24/2015 05:40:50 INFO:	 Starting new HTTP connection (1): builddata.pub.build.mozilla.org
03/24/2015 05:41:21 INFO:	 We have found 1 potential job(s) matching 'Ubuntu VM 12.04 try opt test marionette' on 2d3659c2b21c. We need to trigger more.
03/24/2015 05:41:21 INFO:	 We want to trigger 'Ubuntu VM 12.04 try opt test marionette' on revision '2d3659c2b21c' a total of 1 time(s).
03/24/2015 05:41:21 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/24/2015 05:41:23 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/24/2015 05:41:24 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/24/2015 05:41:33 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/24/2015 05:41:34 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/24/2015 05:41:36 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/24/2015 05:41:43 INFO:	 There is a _build_ job that has completed successfully.
03/24/2015 05:41:48 INFO:	 Starting new HTTP connection (1): ftp.mozilla.org
03/24/2015 05:41:48 INFO:	 Starting new HTTP connection (1): ftp.mozilla.org
03/24/2015 05:41:49 INFO:	 We can trigger the downstream job.
03/24/2015 05:41:49 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/24/2015 05:41:50 INFO:	 Listening on unittest.try.#
03/24/2015 05:52:02 INFO:	 Ubuntu VM 12.04 try opt test marionette completed
03/24/2015 05:52:02 INFO:	 Structured logs for Ubuntu VM 12.04 try opt test marionette available in http://mozilla-releng-blobs.s3.amazonaws.com/blobs/try/sha512/9360a855622ea5cf9f4e8199aee0b187216c30f0e9814994a5d9d62019183d5ce025d10261113ff4534c54edccb989626c0d017d1017b2b2e2783ebab21d9ae4
alice@alice-UX303LN:~/mozilla_ci_tools$

**Comment by armenzg** [comment]
It's making sense so far. Good progress!

What exchange and routing key are you using?
You can use this for testing purposes:
https://tools.taskcluster.net/pulse-inspector

If I use exchange/build/normalized & #.try.# I can see all try pulse messages.
I wonder if the normalized pulse messages only shows completion of jobs.
catlee says that the pulse messages should happen more than just upon completion.
This archive might help you find some answers. You can also post a question on the releng mailing list:
http://people.mozilla.org/~catlee/mozilla-releng-pulsedata/?prefix=build/try-linux64/
https://groups.google.com/forum/#!forum/mozilla.release.engineering

[1]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=2d3659c2b21c&filter-searchStr=Ubuntu VM 12.04 try opt test marionette

**Comment by vaibhavmagarwal** [comment]
Now that we have pulse_actions interacting with Pulse, is this issue still relevant?

**Comment by armenzg** [comment]
Thank you for looking at cleaning up issues!

**Comment by armenzg** [comment]
All done now.
