### ISSUE TITLE
We should recover from an out of date builds-<date>.js

### ISSUE THREAD

**Issue by jmaher** [armenzg/mozilla_ci_tools#135]
output of my script running:
https://pastebin.mozilla.org/8825710

**Comment by vaibhavmagarwal** [comment]
This is the correct pastebin: https://pastebin.mozilla.org/8825713

**Comment by jmaher** [comment]
wrong pastebin:
https://pastebin.mozilla.org/8825720

**Comment by armenzg** [comment]
What do you get if you run: grep "63454875" *js

MacAir ci_tools git:[master] $ grep "63454875" *js
builds-2015-03-04.js:          63454875
builds-2015-03-04.js:          "63454875": 1425506936
builds-2015-03-04.js:        63454875

**Comment by jmaher** [comment]
no results at all :(

**Comment by armenzg** [comment]
Could you please email me your 2015-03-04.js file?

**Comment by vaibhavmagarwal** [comment]
Same error: https://pastebin.mozilla.org/8825734

**Comment by armenzg** [comment]
I explain the situation a bit in here: https://bugzilla.mozilla.org/show_bug.cgi?id=1135991#c11
We need to find code that would verify that a downloaded buildjson file is correct.
For instance, jmaher got a .js file much smaller than it should have been yet we were able to load without raising a proper exception for an invalid json file.

This shows the issue going on:
import requests
import gzip
url = "http://builddata.pub.build.mozilla.org/builddata/buildjson/builds-4hr.js.gz"

req = requests.get(url, stream=True)
content_length = int(req.headers['content-length'])
# I don't think this streams properly
raw = req.raw.read()
download_length = len(raw)
print content_length
print download_length
assert content_length == download_length

**Comment by armenzg** [comment]
NOTE: This code is WIP so please beware that it might have some flawed logic, however, it shows in which direction I was aiming to go:
https://pastebin.mozilla.org/8825775

For now, please delete the .js file on-disk and try again.

Also, another thing that might simply help is if we add stream=True, however, I can't be sure.
https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildjson.py#L24

**Comment by armenzg** [comment]
I will be working on this. I hope to have a fix this week.

**Comment by armenzg** [comment]
I have determined the issue in here.
If I run a script today for jobs that were run today, we will have on disk a builds-...js file for today.
If I run the same thing tomorrow, we will see the file on disk and not fetch it again.
This would cause leaving behind files that don't really have all jobs completed on that day.

In the case where we file a disk on file, we will check that its modification timestamp is newer than the one on the server with:
req = requests.get(url, headers={'If-Modified-Since': last_mod_date}, stream=True)

We will remove files if we get 200 status code and download them again instead of with 304 status code. (Your local file has the same or a newer last modified timestamp than the one of the server)

Commited as https://github.com/armenzg/mozilla_ci_tools/commit/c01fcb8f0c301db33d84a5752f26b2c09007182e
