### ISSUE TITLE
For alltalos.py, do not trigger jobs that the try syntax would have not triggered

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#159]
I will have to think a bit this one.

For instance, if we have not requested Android builds, alltalos.py should not schedule them.

**Comment by priyanklodha** [comment]
How should i go about this, I am completely new to this community and open source.

**Comment by adusca** [comment]
Thank you @priyanklodha ! Unfortunately, this issue was fixed earlier this week and we forgot to change its status, sorry! Would you be interested in working on another issue? #242 can be a good way to get started in this project, or you can take #243 if you are interested in unit testing. If you are not interested in working with Python we can find some other bugs.

The fastest way to get in touch which us is through the [#ateam IRC channel](irc://irc.mozilla.org/ateam), you can ping me (adusca) or armenzg there. The channel is more active during US working hours.

Welcome to mozci!

**Comment by adusca** [comment]
Fixed in #228

**Comment by priyanklodha** [comment]
@adusca  can u give me some other bug to work on. Also i don't have much understanding of code. Actually yesterday only i started with this so if u can help me out with that as well.

**Comment by adusca** [comment]
@priyanklodha Sure! I'm on the #ateam IRC channel right now, can you show up and ping me?

**Comment by adusca** [comment]
Hi @priyanklodha ! Are you still interested in contributing to mozci? I recommend starting with issue #242 to get used to the workflow of this project.
