### ISSUE TITLE
Make it easier for developers to trigger jobs without giving buildername to mozci

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#168]
We had a great discussion on IRC for this issue. I will summarize it here. Basically, developers need to figure out the buildername of a job for triggering the jobs via mozci. However, we can figure out the buildername for them, if they give us other useful information. Now, there are 2 ways to go about this:
1) They give us the Treeherder jobname and branch. For example, for "Linux opt mochitest-browser-chrome-1", we can have --jobname = "Linux opt Mochitest Mochitest M(1)" , --branch = "mozilla-inbound"

2) They give us the platform, testname and branch. Taking the same example as above, it will be:
--platform = "linux opt" --testname = "mochitest-browser-chrome-1" --branch = "mozilla-inbound"

@armenzg , @jmaher, @adusca which method do you prefer? I personally prefer the 2nd option, because it gives us scope to do add more functionality like if the developer specifies just: 
    --testname = "mochitest-browser-chrome-1" --branch = "mozilla-inbound"
then, we can trigger that test on all the platforms (i.e. desktop, android, b2g) which might not be possible in the first method.

If we go with the second method, we would need to create some sort of dynamic mapping to filter the buildernames in steps.

**Comment by adusca** [comment]
For option 2 we could just add something like that to platforms.py:

def find_buildername(test, repo, platform):

right_tests = _filter_builders_matching(fetch_allthethings_data().keys(), test)

repo_and_test =_filter_builders_matching(right_tests, repo)

for buildername in repo_and_test:

if get_associated_platform_name(buildername) == platform:

return buildername

**Comment by armenzg** [comment]
2nd method approach in my opinion should be better. We can start with a POC and re-think if need be.

**Comment by jmaher** [comment]
I would say, make a way to default values for them, specifically repo- you either land on inbound or fxteam.  'linux opt' -> I would prefer linux, and assume opt.

for the case of try server, we should either make it easy to do or default there.  I suspect most developers will want this on try, so maybe the default repo is try.

friendlyretrigger.py --rev <asfd> --testname mochitest-other

I think requiring:
--testname mochitest-devtools-2
or
--testname mochitest-e10s-devtools-2

is bad.  we should make it easy:
--test mochitest --test devtools  <- defaults to all mochitest devtools
--test dt <- translates to mochitest-devtools (but not the chunks)
--test bc1 <- mochitest-browser-chrome-1, mochitest-browser-chrome-e10s-1

we should be able to map easily from human familiar names on the treeherder map -> builder strings.

**Comment by armenzg** [comment]
If it helps, in b2g/tc world they define platform keywords in a .yml file (irrelevant the file format) and that is what it gets used when mach commands are run:
https://dxr.mozilla.org/mozilla-central/source/testing/taskcluster/tasks/branches/mozilla-central/job_flags.yml

**Comment by vaibhavmagarwal** [comment]
We need to get the various platforms, and the testjobs that are active on them for different branches. Does https://secure.pub.build.mozilla.org/builddata/reports/allthethings.json contain all this information? Also, we would like to have names to be short like @jmaher suggested. What is a good way to get this?

**Comment by armenzg** [comment]
allthethings contains all the information for jobs running on buildbot (and not taskcluster - aka some b2g jobs).

I don't know have a suggestion on a good way to generate those shorter names without spending some time in this.

A not thought through proposal:
If we want to trigger builds, use the platform name + type ("opt" by default)
If we want to trigger tests, use the *test* platform name (e.g. win8, win7, xp, mountainlion, linux64) plus short test names (we can have various ways to match rather than 1 to 1 relation) + type ("opt" by default)

**Comment by armenzg** [comment]
In some way I want to use a similar trychooser syntax as possible but given the ability to have more aliases if we see fit.

**Comment by jmaher** [comment]
I like these thoughts in general.  We have to start somewhere- this initial
work will lead to other great ideas.  Lets just make sure we document our
hacks and what is not scalable :)

**Comment by vaibhavmagarwal** [comment]
These is the short form for tests mapping me and @jmaher have arrived at: https://pastebin.mozilla.org/8832069
We use this in SETA project too. This is for all the jobs on desktop (linux, windows, osx) and android which are the platforms we support in MozCI right now. So the usecase of this mapping is:

If a developer inputs: 
--testname M1 --> we will map to "mochitest-1"
whereas if he inputs:
--testname M1 --e10s --> we will map to "mochitest-e10s-1"

Do let me know if this mapping makes sense and we can proceed with it. Then i will proceed for platforms too.

**Comment by vaibhavmagarwal** [comment]
A note: I just realized that I forgot to map talos tests in the above link. Will do that

**Comment by armenzg** [comment]
Are we going to use --e10s as a flag? What else would become a flag?

What do you think ofthis ysyntax?
--platform linux,linux64 --filter m1,e10s --filter gl2
That would match all mochitest-e10s-1 jobs and gl2 jobs for linux and linux64. 

Can we also make sure that all codes are either uppercase or lowercase? That way we have consistency.
For instance R1 vs gl1.

**Comment by vaibhavmagarwal** [comment]
--e10s was just one of the ideas. Your idea also looks good and gives us more control over triggering different kinds of tests (both e10s and  non-e10s) in one command. Also, I will fix the uppercase vs lowercase issue.

**Comment by jmaher** [comment]
yeah, this looks cool!

**Comment by adusca** [comment]
There are 3 different platforms whose platform name is 'macosx64' in allthethings.json:
>>>find_buildernames('try', 'mochitest-1', 'macosx64', debug=False)
['Rev5 MacOSX Mountain Lion 10.8 try opt test mochitest-1',
'Rev4 MacOSX Snow Leopard 10.6 try opt test mochitest-1',
'Rev5 MacOSX Yosemite 10.10 try opt test mochitest-1']

**Comment by armenzg** [comment]
We would normally want to trigger 10.10 since it has more machines to run that pool, hence, getting results faster.
However, we should provide a way to specify each.
In the releng configs we have snowleopard, lion and yosemite as keywords for them.

**Comment by adusca** [comment]
I think we will also need a 'type' key, just having a debug flag is not enough. I wrote a [script](https://pastebin.mozilla.org/8832507) to see if I could attribute a type for every test job based on what appears in its name and turns out that every test job can be classified as either 'debug', 'pgo', 'pgo talos', 'opt', or 'talos' . This is not true for build jobs. Script's results:

Classification of build jobs:
   debug : 192
   pgo : 24
   opt : 8
   None: 1635
Classification of test jobs:
   debug : 4584
   pgo : 1781
   pgo talos : 355
   opt : 6742
   talos : 712

**Comment by armenzg** [comment]
Thank you for using a script to filter through the data. It makes it easier to have conversations.

Let's take a step back to think about how to put the data into buckets for better understanding.
In general, we have three types of builds:
* opt
* leak/debug ("leak" is the name of the build buildernames)
* pgo

For the record, trying to do string matching misses builders like thse (they're put in the None bucket)
WINNT 6.1 x86-64 mozilla-aurora build
WINNT 6.1 x86-64 mozilla-aurora leak test build
Linux x86-64 oak valgrind
linux64-br-haz_try_dep
linux64-sh-haz_try_dep

Notice the linux haz builds don't have the concept of "opt" or "debug".

With regards to downstream buildernames, we have to think into the same categories as the builders.
* "pgo talos" should be considered as "pgo"
* "talos" should be considered "opt"

Talos is not a different type but a test job triggered by an upstream job.

Through this script:
https://pastebin.mozilla.org/8832607

TBH, we only care about "opt", "debug" and "pgo" builds.
We won't try to make all the other builders work in this "easier mode" since those are builders not triggered by a developer push.

Classification of build jobs:
   periodic b2g : 119
   nightly b2g : 103
   pgo b2g : 4
   release release : 353
   b2g : 54
   l10n : 18
   nightly : 102
   bundle: 13
   opt : 483
   opt b2g : 154
   fuzzer : 3
   bundleb2g : 6
   release : 316
   release l10n : 8
   periodic : 9
   None: 16
   pgo : 20
   nightly l10n : 78
Classification of test jobs:
   debug : 4584
   pgo : 1781
   opt : 7809

**Comment by jgraham** [comment]
FWIW I think the way I want this to work is something like

    mozci retrigger cedar 065f57c91e7f --include='web-platform debug'

Where the `--include` option is the same format that treeherder uses (more complex queries could be supported by allowing `--exclude` as well, or something)

**Comment by armenzg** [comment]
@jgraham you mention "retrigger" which would trigger the same job that was run, however, mozci can "arbitrarily trigger". The difference is none from the prespective of running the same commands against the same build and tests.

From your POV, you will have those jobs you want scheduled again.

**Comment by jgraham** [comment]
So I don't quite understand your point, but I don't think it's unreasonable to have different optimisations for retriggering existing jobs vs triggering new jobs if it significantly improves the usability of the tool. Given that in the retrigering case you can just ask treeherder for the existing job details, whereas in the triggering case more user input is required, it seems like it might.

**Comment by armenzg** [comment]
Don't worry about what I said.
retrigger or trigger both are APIs that slight differences.
Re-triggering needs more information to be discovered like request IDs.
At the end, none of the approaches requires more information from the user; only internally.

**Comment by vaibhavmagarwal** [comment]
Closing this issue, as we now have triggerbyfilters.py script.
