### ISSUE TITLE
deploy scripts with pip install

### ISSUE THREAD

**Issue by parkouss** [armenzg/mozilla_ci_tools#175]
for now there is no way to install the files in the scripts folder (https://github.com/armenzg/mozilla_ci_tools/tree/master/scripts) with a regular pip install. it would be good to add these helpul scripts!

A good naming convention could be to add 'mozci-' at the beginning of the script name. For example, mozci-trigger.

One could use setuptools entry_points to make this happen - it will create the right stuff for all OS, and put the files at the right place (using virtualenv or not). Mozregression does this for example: https://github.com/mozilla/mozregression/blob/master/setup.py#L22
This woud require the scripts to be placed under the package though.

**Comment by parkouss** [comment]
Yep, forgot to tell that for me it would be usefull to have access to trigger.py.

**Comment by vaibhavmagarwal** [comment]
I am working on this.

**Comment by vaibhavmagarwal** [comment]
We will need to move the 'scripts' directory inside of mozci directory, if we want to package it with pip. The reason is otherwise the 'scripts' directory gets installed in /usr/local/lib/python2.7/ instead of /usr/local/lib/python2.7/mozci . Now, since scripts directory is specific to mozci, we should ideally have it inside  /usr/local/lib/python2.7/mozci directory.

@armenzg , @jmaher , @chmanchester thoughts?

**Comment by armenzg** [comment]
It works for me.
It's OK with me to move the scripts/ directory under mozci/
We will need to update the scripts page for the docs.

**Comment by armenzg** [comment]
I just merged @vaibhavmagarwal 's work. Please let us know if this helps.

**Comment by vaibhavmagarwal** [comment]
We will be required to do a new release for testing this, imo. Though no hurry.

**Comment by armenzg** [comment]
I'm doing the release today. Closing now.

**Comment by parkouss** [comment]
Thank you guys!
