### ISSUE TITLE
Periodically generate a list of jobs on try that fail 100% of the time

### ISSUE THREAD

**Issue by chmanchester** [armenzg/mozilla_ci_tools#233]
This would be a stopgap for https://bugzilla.mozilla.org/show_bug.cgi?id=1137370

**Comment by armenzg** [comment]
I've asked catlee to see if we can use reportor.

Build a service that every night updates which jobs fail 100% of the time.

There are many many ways that this can be built. We can also use TH for status. In fact, it might be a more efficient type of code.

We need to determine what are the list of try builders [1]
We need to find the status on a number of revisions on try where it run (TH probably would be better at getting this info internally).
If we have 10 out of 10 jobs with failed status we should consider it 100% failure.
If 9/10, we should grab more data points just in case that we happened to grab data of someone trying to fix the suite.


[1] builders = _filter_builders_matching(fetch_allthethings_data()['builders'], " try ")

**Comment by adusca** [comment]
I'll work on this.

**Comment by armenzg** [comment]
Thanks Alice!

**Comment by adusca** [comment]
I have been playing with ActiveData for this. Since it only deals with tests that have structured logging, I don't know if it is a good solution for this. But it allows us to create some cool tables. Bellow are all the tests on try with a success rate smaller then 20%:


buildername|success|warnings|failure|retry|exception|cancelled|success rate
----------------|----------|-----------|--------|--------|-----------|---------|---------------
b2g_emulator_vm try opt test marionette|0|1|65|0|0|0|0.00%
Android 4.3 armv7 API 11+ try debug test robocop-1|1|1651|0|3|0|0|0.06%
Rev4 MacOSX Snow Leopard 10.6 try debug test web-platform-tests-4|4|5528|2|0|0|0|0.07%
Ubuntu VM 12.04 try debug test web-platform-tests-4|14|5542|3|0|0|0|0.25%
Rev5 MacOSX Yosemite 10.10 try debug test web-platform-tests-3|5|857|0|0|0|0|0.58%
Ubuntu VM 12.04 x64 try debug test web-platform-tests-4|26|4453|3|0|0|0|0.58%
Windows 7 32-bit try debug test web-platform-tests-8|123|2946|7|0|0|0|4.00%
Android 4.3 armv7 API 11+ try debug test robocop-4|57|1101|0|11|0|0|4.88%
Windows XP 32-bit try debug test web-platform-tests-8|181|3512|7|0|0|0|4.89%
Rev5 MacOSX Yosemite 10.10 try opt test web-platform-tests-3|60|780|0|0|0|0|7.14%
Windows 8 64-bit try debug test web-platform-tests-8|585|2966|5|0|1|0|16.45%

**Comment by adusca** [comment]
You can generate a table like the one above doing:
```
python mozci/scripts/misc/results_per_suite.py BRANCH
```
This generates a file called results_per_suite_BRANCH.csv. @chmanchester Do you also need the results for suites without structured logging?

**Comment by armenzg** [comment]
I created a cronjob for the giggles that exercises this script:
http://people.mozilla.org/~armenzg/permanent/results_per_suite_try.txt

**Comment by armenzg** [comment]
Thanks @adusca!
