### ISSUE TITLE
Have a good way to deal with disappeared job in MozCI

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#289]
Right now we show a BuildjsonExcpetion error: https://pastebin.mozilla.org/8838870 which is not a good way to deal with a disappeared job, if we want mozci to be part of longer running services like trigger-bot and pulse-actions. In my opinion, we should have a default way to ignore it (like we do in coalesced mode) and print a message that we are doing so. Thoughts?

**Comment by adusca** [comment]
We get a BuildjsonException when we are trying to determine the status of a job and we don't find a job with the right request_id in builds-*.js.

We need to think about if it is safe to treat disappeared jobs as 'running' or something else. Disappeared jobs can't be treated as 'completed' because we cannot find the files for them (this matter for build jobs), but they can't be treated as non-existent either because that way we would trigger jobs that we are not supposed to trigger.

I'm not sure if the only time a job disappears is when its status changes. If that is the case, treating them as 'running' seems harmless.

**Comment by vaibhavmagarwal** [comment]
This is a slightly different example (but the same question): https://pastebin.mozilla.org/8838902
We do not have "requests" keyword in status_info

**Comment by vaibhavmagarwal** [comment]
We call query_job_data function at 2 places:
[1] - https://github.com/armenzg/mozilla_ci_tools/blob/22046937cfb9dba0b1fdcb5f48fd54edef01f2fe/mozci/query_jobs.py#L104

[2] - https://github.com/armenzg/mozilla_ci_tools/blob/14eb588af1eae9303486fb2e6ffc972a2d88b335/mozci/mozci.py#L195

In [1], we should note that the job already has a 'SUCCESS' job_status before being queried for, so I think having them marked as 'running' is not correct.

**Comment by adusca** [comment]
Buildapi is a bit weird. It will change the status is one place from 'null' to '0' before updating the values in builds-4hr.js.

Usually a job disappears from builds-4hr.js when it is changing status, so it is common for a disappeared job to have a 'SUCCESS' status.

The only place in which we treat completed and running jobs differently is when we are looking for the status of upstream jobs. In one case we look for files, in the other we do nothing and tell the user to wait. We cannot consider disappeared jobs successful because we are not able to find files for them, we still have to wait until Buildapi updates its other database to be able to do anything.

**Comment by vaibhavmagarwal** [comment]
This issue should be fixed in https://github.com/armenzg/mozilla_ci_tools/pull/290 and https://github.com/armenzg/mozilla_ci_tools/pull/297 .. Will reopen if I see this again.
