### ISSUE TITLE
The string representation of a UTC time should include UTC in it

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#44]
Currently:
>>> from mozci.utils.tzone import utc_time, pacific_time
>>> pacific_time()
'Tue, 24 Feb 2015 08:22:01 -0800 (PST)'
>>> utc_time()
'Tue, 24 Feb 2015 16:23:22  ()'

What I expect:
>>> utc_time()
'Tue, 24 Feb 2015 16:23:22 -0000 (UTC)'

**Comment by valeriat** [comment]
Thanks! I would like to try.

**Comment by vaibhavmagarwal** [comment]
Hi @valeriat, thanks for your interest in this bug!

To solve this bug, you will need to do 2 things:

1) Make utc_dt function[1] similar to pacific_time function[2]. So define universal_tz instead of pacific_tz.

2) Define Universal class like Pacific class[3].

[1] - https://github.com/armenzg/mozilla_ci_tools/blob/fa4ca3c536746a6168e1968c0325965404a185ca/mozci/utils/tzone.py#L92
[2] - https://github.com/armenzg/mozilla_ci_tools/blob/fa4ca3c536746a6168e1968c0325965404a185ca/mozci/utils/tzone.py#L70
[3] - https://github.com/armenzg/mozilla_ci_tools/blob/fa4ca3c536746a6168e1968c0325965404a185ca/mozci/utils/tzone.py#L60

This should solve the bug. To test, just call pacific_time() and utc_time() function in any script inside scripts/ folder. Let me know how it goes and if you need any help!

**Comment by valeriat** [comment]
Thank you, vaibhavmagarwal! 
There is one more problem with PST. We calculate time and then we determine format, so there is transition from DST to standart timet at 01:00:00 PDT not PST.

For example: 
Sun, 25 Oct 2015 00:59:59 -0700 (PDT) then Sun, 25 Oct 2015 01:00:00 -0800 (PST)
Sun, 25 Oct 2015 01:59:59 -0800 (PST) then Sun, 25 Oct 2015 01:00:00 -0800 (PST) 
Time offset is correct but PDT - PST transition is late for an hour.

**Comment by vaibhavmagarwal** [comment]
I see. There maybe some error in logic in the pdt and pst conversion. @valeriat can you look into tzone.py and figure out what is going wrong?
@armenzg do you see the same issue and can you help here?

**Comment by armenzg** [comment]
Is this how it should work?
On 2015/10/25 at 1:59am we're still in PST
a minute later we should be:
2015/10/25 at 1:00am we're then in PDT ("We gain one hour back")

Could you please paste some code to show how you generated that output?
I would not be surprised if the tzone code is not right.

Dates and times are hard.

http://www.timeanddate.com/time/dst/
"Daylight Saving Time (DST) is a way of making better use of the natural daylight by setting your clock forward one hour during the summer months, and back again in the fall."
"You set your clock forward in the spring when DST starts (= lose one hour), and back one hour when DST ends in the fall (= regain one hour)."

**Comment by armenzg** [comment]
This has now been fixed.
Thanks @valeriat and @vaibhavmagarwal for the reviews!
