### ISSUE TITLE
Allow determining the repo_url of a repo_name without LDAP credentials

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#73]
We currently talk with buildapi to determine the list of repositories, however, that requires LDAP credentials.

We can figure out the repo_url by constructing it based on allthethings.json.

If we iterate through the list of builders [1] we can build a dictionary with the branch as the key (aka repo_name) and concatening hg.m.o with repo_path as the value.

This important to fix for tools like alert_manager and not requirying its contributors to get L1 commit level.

[1] https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/allthethings.py#L12

**Comment by vaibhavmagarwal** [comment]
I'll work on this

**Comment by adusca** [comment]
query_repo_url needs credentials because query_repositories downloads from this page:
https://secure.pub.build.mozilla.org/buildapi/self-serve/branches?format=json 
that requires credentials.

But when there is already a repositories.txt file query_repositories just uses that and does not download anything (when clobber=False). So if we provided a requirements.txt file there would be no need for credentials. The problem with that we would have to keep updating repositories.txt.

**Comment by vaibhavmagarwal** [comment]
@adusca yes, that is the reason. @armenzg has said that constructing it from allthethings.json can be another way, but having a repositories.txt file seems like an easier way out. I am not sure which way will be preferred.

**Comment by armenzg** [comment]
Having a commited repositories.txt will be good for some time, however, in the future it will fall out of date when new repositories are added. Perhaps we can live with it and add them case for case.

At least we would remove the need for credentials.

**Comment by armenzg** [comment]
We're OK in here.
